--script do banco

CREATE TABLE BILLING (
BILLCODE INTEGER NOT NULL,
DESCRIPTION VARCHAR(100) NOT NULL,
VALUE DOUBLE NOT NULL,
EXPIRATIONDATE DATE NOT NULL,
PAIDDATE DATE NOT NULL,
PRIMARY KEY (BILLCODE)
);